apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 5
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
      - name: myjavaapp
        image: maha4iac/mahalogin:1 
        ports:
        - containerPort: 8080